# Generated by Django 6.0.6 on 2026-06-07 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characterization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('os_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='characterization.network')),
            ],
        ),
        migrations.CreateModel(
            name='OpenPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField()),
                ('protocol', models.CharField(default='tcp', max_length=10)),
                ('service_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(default='open', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_ports', to='hosts.host')),
            ],
            options={
                'unique_together': {('host', 'port_number', 'protocol')},
            },
        ),
    ]
