# Generated by Django 6.0.6 on 2026-06-07 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=100)),
                ('config_file', models.FileField(upload_to='configs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(help_text='e.g., TELNET_ENABLED', max_length=100, unique=True)),
                ('pattern', models.CharField(help_text='The regular expression pattern to match against.', max_length=255)),
                ('severity', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('description', models.TextField(help_text='Detailed context shown to the user on findings.')),
                ('is_active', models.BooleanField(default=True, help_text='Easily toggle this signature rule on/off.')),
            ],
        ),
        migrations.CreateModel(
            name='ACLRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acl_name', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('permit', 'Permit'), ('deny', 'Deny')], max_length=10)),
                ('protocol', models.CharField(max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('destination_port', models.CharField(blank=True, max_length=50)),
                ('device_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acl_rules', to='characterization.deviceconfig')),
            ],
        ),
        migrations.AddField(
            model_name='deviceconfig',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='characterization.network'),
        ),
        migrations.CreateModel(
            name='SecurityFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='characterization.deviceconfig')),
                ('signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characterization.securitysignature')),
            ],
        ),
    ]
