# Generated by Django 6.0.6 on 2026-06-07 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('pattern_snapshot', models.CharField(max_length=255)),
                ('severity_snapshot', models.CharField(max_length=10)),
                ('description_snapshot', models.TextField()),
                ('backed_up_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('original_signature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='characterization.securitysignature')),
            ],
            options={
                'ordering': ['-backed_up_at'],
            },
        ),
    ]
