# Generated by Django 6.0.6 on 2026-06-08 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterization', '0002_signaturebackup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr_block', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subnets', to='characterization.network')),
            ],
            options={
                'unique_together': {('network', 'cidr_block')},
            },
        ),
    ]
