# Generated by Django 6.0.6 on 2026-06-08 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterization', '0003_subnet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArpEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
                ('ip_address', models.GenericIPAddressField()),
                ('gathered_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arp_entries', to='characterization.deviceconfig')),
            ],
            options={
                'unique_together': {('ip_address', 'gathered_from')},
            },
        ),
    ]
