# Generated by Django 6.0.6 on 2026-06-08 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterization', '0004_arpentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aclrule',
            name='action',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='aclrule',
            name='destination',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aclrule',
            name='source',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='RouterObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=255)),
                ('object_type', models.CharField(max_length=50)),
                ('value', models.TextField()),
                ('device_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='router_objects', to='characterization.deviceconfig')),
            ],
        ),
    ]
