# Generated by Django 6.0.6 on 2026-06-08 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterization', '0005_alter_aclrule_action_alter_aclrule_destination_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routerobjects',
            old_name='value',
            new_name='contents',
        ),
        migrations.AlterField(
            model_name='routerobjects',
            name='device_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routerObjects', to='characterization.deviceconfig'),
        ),
        migrations.AlterField(
            model_name='routerobjects',
            name='object_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='routerobjects',
            name='object_type',
            field=models.CharField(default='Network', max_length=255),
        ),
    ]
