# Generated by Django 6.0.6 on 2026-06-09 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterization', '0006_rename_value_routerobjects_contents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('member_type', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=100)),
                ('device_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characterization.deviceconfig')),
            ],
        ),
    ]
