# Generated by Django 6.0.6 on 2026-06-10 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterization', '0007_networkobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_interface', models.CharField(max_length=100)),
                ('target_interface', models.CharField(max_length=100)),
                ('vlan_list', models.CharField(max_length=255)),
                ('source_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uplinks', to='characterization.deviceconfig')),
                ('target_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downlinks', to='characterization.deviceconfig')),
            ],
        ),
    ]
