# Generated by Django 6.0.6 on 2026-06-10 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characterization', '0008_infrastructurelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructurelink',
            name='target_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downlinks', to='characterization.deviceconfig'),
        ),
        migrations.AlterField(
            model_name='infrastructurelink',
            name='target_interface',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
