# Generated by Django 6.0.6 on 2026-06-07 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characterization', '0001_initial'),
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(help_text='e.g., GigabitEthernet1/0/21', max_length=100)),
                ('mac_address', models.CharField(help_text='e.g., 001a.a22b.11c4 or 00:1a:a2:2b:11:c4', max_length=17)),
                ('vlan_id', models.IntegerField(default=1)),
                ('connected_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switch_attachments', to='hosts.host')),
                ('infrastructure_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_endpoints', to='characterization.deviceconfig')),
            ],
            options={
                'unique_together': {('infrastructure_device', 'interface_name', 'mac_address')},
            },
        ),
    ]
