# Generated by Django 6.0.6 on 2026-06-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portattachment',
            name='ip',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
